services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-open_garage}
      POSTGRES_USER: ${POSTGRES_USER:-open_garage_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - open-garage-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/src
    command: gunicorn --chdir /app/src settings.wsgi:application --bind 0.0.0.0:8000 --workers 3
    environment:
      - PYTHONPATH=/app/src
      - DJANGO_STATIC_ROOT=/staticfiles
    env_file:
      - ./src/.env
    depends_on:
      - db
    ports:
      - '8000:8000'
    volumes:
      - .:/app:Z
    networks:
      - open-garage-network

volumes:
  postgres_data:

networks:
  open-garage-network:
    driver: bridge
