services:
  db:
    image: postgres:18
    env_file:
      - ./src/.env
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-open_garage_user} -d ${POSTGRES_DB:-open_garage}']
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - open-garage-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/src
    command: gunicorn --chdir /app/src settings.wsgi:application --bind 0.0.0.0:8000 --workers 3
    environment:
      - PYTHONPATH=/app/src
      - DJANGO_STATIC_ROOT=/staticfiles
    env_file:
      - ./src/.env
    depends_on:
      - db
    ports:
      - '8000:8000'
    volumes:
      - .:/app:Z
    networks:
      - open-garage-network

volumes:
  postgres_data:

networks:
  open-garage-network:
    driver: bridge
