[project]
name = "open-car-fleet"
version = "0.1.0"
description = ""
authors = [
    {name = "Jean-Francois Labonte",email = "jeff.labonte12@gmail.com"}
]
license = {text = "GPLv3"}
requires-python = ">=3.12"
dependencies = [
    "django (>=6.0.8,<7.0.0)",
    "django-pytest (>=0.2.0,<0.3.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "requests (>=2.32.0,<3.0.0)",
    "gunicorn (>=22.0,<27.0)",
    "psycopg[binary] (>=3.3,<4.0)",
    "whitenoise (>=6.12.0,<7.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.test.dependencies]
pytest-cov = ">=7.0.0,<8.0.0"
pytest-bdd = ">=8.1.0,<9.0.0"
pytest-django = ">=4.11.0,<5.0.0"
pytest-env = ">=1.1.5,<2.0.0"

[tool.poetry.group.e2e]
optional = true

[tool.poetry.group.e2e.dependencies]
selenium = ">=4.35.0,<5.0.0"
