[project]
name = "open-car-fleet"
version = "0.1.0"
description = ""
authors = [
    {name = "Jean-Francois Labonte",email = "jeff.labonte12@gmail.com"}
]
license = {text = "GPLv3"}
requires-python = ">=3.12"
dependencies = [
    "django (>=6.0.8,<7.0.0)",
    "django-pytest (>=0.2.0,<0.3.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "requests (>=2.32.0,<3.0.0)",
    "gunicorn (>=22.0,<27.0)",
    "psycopg[binary] (>=3.3,<4.0)",
    "whitenoise (>=6.12.0,<7.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"