# Generated by Django 6.0.8 on 2026-08-06 00:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='is_mechanic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='mechanic_promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='workjob',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_garages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'garage',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='shop.garage'),
        ),
        migrations.CreateModel(
            name='GarageInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_garage_invitations', to=settings.AUTH_USER_MODEL)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='shop.garage')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_garage_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'garage_invitation',
            },
        ),
        migrations.CreateModel(
            name='GarageMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='shop.garage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'garage_membership',
            },
        ),
        migrations.AddField(
            model_name='garage',
            name='members',
            field=models.ManyToManyField(related_name='garages', through='shop.GarageMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KnownShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'known_shop',
                'indexes': [models.Index(fields=['name'], name='known_shop_name_16f158_idx')],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='shop.knownshop'),
        ),
        migrations.AddField(
            model_name='workjob',
            name='assigned_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_jobs', to='shop.knownshop'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_to__isnull', False), ('assigned_shop__isnull', False), _negated=True), name='report_single_assignment_target'),
        ),
        migrations.AddConstraint(
            model_name='workjob',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_to__isnull', False), ('assigned_shop__isnull', False), _negated=True), name='workjob_single_assignment_target'),
        ),
        migrations.AddIndex(
            model_name='garageinvitation',
            index=models.Index(fields=['invited_email'], name='garage_invi_invited_0dcf69_idx'),
        ),
        migrations.AddIndex(
            model_name='garageinvitation',
            index=models.Index(fields=['status', 'expires_at'], name='garage_invi_status_8d2ef3_idx'),
        ),
        migrations.AddConstraint(
            model_name='garageinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('garage', 'invited_email'), name='uniq_pending_invitation_per_garage_email'),
        ),
        migrations.AlterUniqueTogether(
            name='garagemembership',
            unique_together={('garage', 'user')},
        ),
    ]
