# Generated by Django 6.0.8 on 2026-08-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
