# Generated by Django 6.0.8 on 2026-08-10 17:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_align_car_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='colour',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('upload', 'Uploaded file'), ('external', 'External link')], default='upload', max_length=20)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('link', 'Link')], default='document', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='report_attachments/%Y/%m/%d')),
                ('url', models.URLField(blank=True, default='')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shop.report')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
