# Generated by Django 6.0.8 on 2026-09-08

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_knownshopproof'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopuser',
            constraint=models.UniqueConstraint(
                Lower('email'),
                condition=~models.Q(email=''),
                name='shop_user_unique_nonempty_email_ci',
            ),
        ),
    ]
