# Generated by Django 6.0.8 on 2026-09-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_shopuser_unique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownshop',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_known_shops',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
