# Generated by Django 6.1 on 2026-09-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_attachment_uploaded_by_alter_attachment_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
