# Generated by Django 6.0.8 on 2026-08-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardoc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='car_docs/'),
        ),
    ]
