"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_dotenv(path: Path) -> None:
    if not path.exists():
        return

    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        name, value = line.split('=', 1)
        name = name.strip()
        value = value.strip().strip('"').strip("'")

        if name and name not in os.environ:
            os.environ[name] = value

# Load environment settings from .env first, then fall back to the checked-in template.
env_paths = [
    BASE_DIR / '.env',
    BASE_DIR / '.env.template',
    BASE_DIR.parent / '.env',
    BASE_DIR.parent / '.env.template',
]
for env_path in env_paths:
    load_dotenv(env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').strip().lower() in ('1', 'true', 'yes')


# SECURITY WARNING: keep the secret key out of source control.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be configured.')
if not DEBUG and SECRET_KEY in {'django-insecure-change-me', 'change-me'}:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must not use a development placeholder.')

HANKO_API_URL = os.environ.get('HANKO_API_URL', '').strip()

allowed_hosts_raw = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost 127.0.0.1 [::1]').strip()
ALLOWED_HOSTS = allowed_hosts_raw.split() if allowed_hosts_raw else ['localhost', '127.0.0.1', '[::1]']
if '*' in ALLOWED_HOSTS and not DEBUG:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS must not contain * when DEBUG is disabled.')

csrf_trusted_origins_raw = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
)
if csrf_trusted_origins_raw:
    origins = []
    for item in csrf_trusted_origins_raw.replace(',', ' ').split():
        item = item.strip()
        if not item:
            continue
        if item.startswith('http://') or item.startswith('https://'):
            origins.append(item)
        else:
            origins.append(f'https://{item}')
            if item.startswith(('localhost', '127.0.0.1', '[::1]')):
                origins.append(f'http://{item}')
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(origins))
else:
    CSRF_TRUSTED_ORIGINS = []

trusted_proxy = os.environ.get('DJANGO_TRUSTED_PROXY', 'False').strip().lower() in ('1', 'true', 'yes')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if trusted_proxy else None
USE_X_FORWARDED_HOST = trusted_proxy and os.environ.get('DJANGO_USE_X_FORWARDED_HOST', 'False').strip().lower() in ('1', 'true', 'yes')
USE_X_FORWARDED_PORT = trusted_proxy and os.environ.get('DJANGO_USE_X_FORWARDED_PORT', 'False').strip().lower() in ('1', 'true', 'yes')

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', str(not DEBUG)).strip().lower() in ('1', 'true', 'yes')
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', str(not DEBUG)).strip().lower() in ('1', 'true', 'yes')
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').strip().lower() in ('1', 'true', 'yes')
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'car_docs',
]

AUTH_USER_MODEL = 'shop.ShopUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'shop.middleware.HankoAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'settings.urls'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.theme',
                'shop.context_processors.language_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB'),
            'USER': os.environ.get('POSTGRES_USER', 'open_garage_user'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'en-ca'

LANGUAGES = [
    ('en-ca', _('English')),
    ('fr-ca', _('Français')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.environ.get('DJANGO_STATIC_ROOT', str(BASE_DIR / 'staticfiles')))
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [
    BASE_DIR / 'public',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email (Mailgun HTTP API)
# https://documentation.mailgun.com/en/latest/api-sending.html#sending

EMAIL_BACKEND = 'shop.mailgun_backend.MailgunEmailBackend'
MAILGUN_API_KEY = os.environ.get('MAILGUN_API_KEY', '')
MAILGUN_SANDBOX_DOMAIN = os.environ.get('MAILGUN_SANDBOX_DOMAIN', '')
MAILGUN_BASE_DOMAIN = os.environ.get('MAILGUN_BASE_DOMAIN', 'https://api.mailgun.net')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    f'Open Car Fleet <postmaster@{MAILGUN_SANDBOX_DOMAIN or "localhost"}>',
)
